### ISSUE TITLE
Preview available? 

### ISSUE THREAD

**Issue by SidVal** [SamSaffron/discourse-simple-theme#1]
@SamSaffron, please check the preview's link from https://meta.discourse.org/t/sams-personal-minimal-topic-list-design/23552, the link: https://meta.discourse.org/?preview-style=589a2b8f-237f-4408-b86b-2d5f158b22b6 does not work anymore.

Can you give an other link to preview themes? :pray:

**Comment by SamSaffron** [comment]
I will fix the preview stuff ... but none of this has anything to do with this specific theme :)

**Comment by SidVal** [comment]
Yeap, sorry, not an issue here, my bad. :-1:
